on:
  workflow_call:
    inputs:
      if:
        description: 'Whether to run this job'
        required: false
        type: boolean
      os:
        required: true
        type: string
      image:
        required: true
        type: string
      reference:
        required: true
        type: string
jobs:
  reusable-build-deps-with-container:
    if: ${{ inputs.if }}
    runs-on: ${{ inputs.os }}
    container:
      image: ${{ inputs.image }}
    steps:
      - uses: actions/checkout@v3
      - if: ${{ inputs.reference != 'null' }}
        uses: ./.github/actions/setup-conan
      - if: ${{ inputs.reference != 'null' }}
        uses: ./.github/actions/setup-kthbuild
      - if: ${{ inputs.reference != 'null' }}
        # run: conan user -p ${{ secrets.CONAN_PASSWORD }} -r $CONAN_REMOTE ${{ secrets.CONAN_LOGIN_USERNAME }}
        run: conan remote login -p ${{ secrets.CONAN_PASSWORD }} $CONAN_REMOTE ${{ secrets.CONAN_LOGIN_USERNAME }}
      - name: download
        if: ${{ inputs.reference != 'null' }}
        uses: actions/download-artifact@v3
        with:
          name: conan-lockfile
      - name: build
        if: ${{ inputs.reference != 'null' }}
        run: conan install --requires=${{ inputs.reference }} -l conan.lock -b missing
      - name: upload
        if: ${{ inputs.reference != 'null' }}
        run: conan upload ${{ inputs.reference }} -r $CONAN_REMOTE # --all
      - run: exit 0
