on:
  workflow_call:
    inputs:
      if:
        description: 'Whether to run this job'
        required: false
        type: boolean
      os:
        required: true
        type: string
      image:
        required: true
        type: string
      xxx:
        required: true
        type: string
jobs:
  reusable-build-deps-with-container:
    if: ${{ inputs.if }}
    runs-on: ${{ inputs.os }}
    container:
      image: ${{ inputs.image }}
        # echo "CONAN_DOCKER_IMAGE=conanio/gcc${{ matrix.config.version }}${{ matrix.config.docker_suffix }}" >> $GITHUB_ENV

    steps:
      - name: Print Other
        run: |
          echo "Other     ${{ input.xxx }}"

      # - uses: actions/checkout@v3
      # - if: ${{ matrix.reference != 'null' }}
      #   uses: ./.github/actions/setup-conan
      # - if: ${{ matrix.reference != 'null' }}
      #   uses: ./.github/actions/setup-kthbuild
      # - if: ${{ matrix.reference != 'null' }}
      #   # run: conan user -p ${{ secrets.CONAN_PASSWORD }} -r $CONAN_REMOTE ${{ secrets.CONAN_LOGIN_USERNAME }}
      #   run: conan remote login -p ${{ secrets.CONAN_PASSWORD }} $CONAN_REMOTE ${{ secrets.CONAN_LOGIN_USERNAME }}
      # - name: download
      #   if: ${{ matrix.reference != 'null' }}
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: conan-lockfile
      # - name: build
      #   if: ${{ matrix.reference != 'null' }}
      #   run: conan install --requires=${{ matrix.reference }} -l conan.lock -b missing
      # - name: upload
      #   if: ${{ matrix.reference != 'null' }}
      #   run: conan upload ${{ matrix.reference }} -r $CONAN_REMOTE # --all
      # - run: exit 0
